swagger: '2.0'
info:
  title: PWWW Rest API
  version: 1.0.0
  description: RESTful API for PWWW
host: testing
basePath: /
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /recordings:
    get:
      operationId: getAllRecordings
      description: Returns names of all saved recordings
      responses:
        '200':
          $ref: '#/responses/RecordingList'
  '/recording/{id}':
    get:
      operationId: getRecording
      description: Returns recording in JSON Format
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          minimum: 0
          description: The recording ID
      responses:
        '200':
          $ref: '#/responses/Recording'
responses:
  RecordingList:
    description: List of recordings
    schema:
      type: array
      items:
        type: object
        properties:
          id:
            type: integer
            minimum: 0
          name:
            type: string
          created_on:
            type: string
            format: date-time
  Recording:
    description: PWWW recording
    schema:
      type: object
      properties:
        id:
          type: integer
          minimum: 0
        name:
          type: string
        created_on:
          type: string
          format: date-time
        recording:
          type: array
          items:
            type: object
