name: Build server and React App

on:
  push:
    branches: [ development ]
    
  workflow_dispatch:

jobs:
  build-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Install node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies and build project
        run : |
          cd $GITHUB_WORKSPACE/backend/tools
          sudo chmod +x ./build.sh
          sudo ./build.sh

      - name: Copy REST server files into build folder
        run: |
          sudo cp -r $GITHUB_WORKSPACE/backend/src/pwww-server/ $GITHUB_WORKSPACE/backend/build/src

      - name: Upload built server project as a job artifact
        uses: actions/upload-artifact@v2
        with:
          name: pwww-server
          path: |
            ${{github.workspace}}/backend/build/src
  
  build-react:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Install node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install project and dependencies
        run : |
          cd $GITHUB_WORKSPACE/frontend
          sudo npm install .
      
      - name: Build React App
        run: |
          cd $GITHUB_WORKSPACE/frontend
          sudo npm run build
      
      - name: Upload built app as a job artifact
        uses: actions/upload-artifact@v2
        with:
          name: pwww-client
          path: ${{github.workspace}}/frontend/build/
