name: Build Application

on:
  push:
    branches: [ development ]
    
  workflow_dispatch:

jobs:
  build-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Install node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: (Server) Install dependencies and build project
        run : |
          cd $GITHUB_WORKSPACE/backend/tools
          sudo chmod +x ./build.sh
          sudo ./build.sh

      - name: (React) Install project and dependencies
        run : |
          cd $GITHUB_WORKSPACE/frontend
          sudo npm install .
      
      - name: (React) Build React App
        run: |
          cd $GITHUB_WORKSPACE/frontend
          sudo npm run build
      
      - name: (React) Copy app to server folder
        run: |
          sudo mv $GITHUB_WORKSPACE/frontend/build/ $GITHUB_WORKSPACE/backend/build/www

      - name: Upload built app as a job artifact
        uses: actions/upload-artifact@v2
        with:
          name: pwww-server
          path: |
            ${{github.workspace}}/backend/build